version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - python --version
      - python -m py_compile app.py

  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
