version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running tests
      - python -m py_compile app.py   # simple test

  build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
